name: ARSplatoonGame
options:
  bundleIdPrefix: com.arsplatoon
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: ja
  
settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    SUPPORTS_MACCATALYST: false
    SWIFT_EMIT_LOC_STRINGS: true
    
targets:
  ARSplatoonGame:
    type: application
    platform: iOS
    sources:
      - path: Sources
        excludes:
          - "**/*.md"
    resources:
      - path: Resources
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: Domain
      - package: Application  
      - package: Infrastructure
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.arsplatoon.game
        INFOPLIST_FILE: Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: true
        # ARKit requirements
        ARKIT_REQUIRED: true
        # Camera usage
        NSCameraUsageDescription: "このアプリはARゲームのためにカメラを使用します"
        NSLocalNetworkUsageDescription: "このアプリは近くのプレイヤーとの対戦のためにローカルネットワークを使用します"
        # Code signing for development
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_COMPILATION_MODE: wholemodule
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          
  ARSplatoonGameTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/ARSplatoonGameTests
    dependencies:
      - target: ARSplatoonGame
      - package: TestSupport
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        PRODUCT_BUNDLE_IDENTIFIER: com.arsplatoon.game.tests
      
  ARSplatoonGameUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: Tests/ARSplatoonGameUITests
    dependencies:
      - target: ARSplatoonGame
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        PRODUCT_BUNDLE_IDENTIFIER: com.arsplatoon.game.uitests

packages:
  Domain:
    path: Packages/Domain
  Application:
    path: Packages/Application
  Infrastructure:
    path: Packages/Infrastructure
  TestSupport:
    path: Packages/TestSupport

schemes:
  ARSplatoonGame:
    build:
      targets:
        ARSplatoonGame: all
        ARSplatoonGameTests: [test]
        ARSplatoonGameUITests: [test]
    run:
      config: Debug
      commandLineArguments:
        "-com.apple.CoreData.ConcurrencyDebug": "1"
    test:
      config: Debug
      targets:
        - ARSplatoonGameTests
        - ARSplatoonGameUITests
      commandLineArguments:
        "-com.apple.CoreData.ConcurrencyDebug": "1"
    archive:
      config: Release

fileGroups:
  - Sources
  - Resources
  - Tests
  - Packages